### ISSUE TITLE
INFOGRAFIA ACTIVIDAD 2

### ISSUE THREAD

**Issue by YaelTrinidad** [SistemasTecTlaxiaco/actividad-2-infografia-YaelTrinidad#1]
[INFOGRAFIA CONOCIMIENTO YAEL.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-infografia-YaelTrinidad/files/9448036/INFOGRAFIA.CONOCIMIENTO.YAEL.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
De acuerdo a la rúbrica, has obtenido un 17.6% del 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
